version: 2
updates:
- package-ecosystem: npm
  directory: "/javascript"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/ruby"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
